name: NestConsumer CI/CD
on:
  push:
    branches:
       - main
  pull_request:
    branches: 
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        PACT_BROKER_URL: https://pact-broker.int.k8s.getmobee.com/
        PACT_MOCK_URL: http://localhost:3500 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: confirm Variables
        run: echo Hello world ${{secrets.pactBrokerUsername}} $PACT_BROKER_URL $GITHUB_SHA
      - name: Install & Tests
        run: |
          npm install
          npm test
      - name: Build Image
        run: docker build -t loneconsumer .
      - name: Run Builded Image
        run: docker run -d -p 3001:3001 --env PACT_BROKER_URL=$PACT_BROKER_URL --env PACT_BROKER_PASSWORD=${{secrets.pactBrokerPassword}} --env PACT_BROKER_USERNAME=${{secrets.pactBrokerUsername}} --env CONSUMER_VERSION=$GITHUB_SHA --env PACT_MOCK_URL=$PACT_MOCK_URL --env PROVIDER_URL=http://localhost:3000 --name loneconsumercontainer  -t loneconsumer 
      - name: Publish the Pacts To the Broker
        run: docker exec loneconsumercontainer npm run publish:pact 
