name: NestConsumer CI/CD
on:
  push:
    branches:
       - master
  pull_request:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        PACT_BROKER_URL: https://pact-broker.int.k8s.getmobee.com/
        PACT_MOCK_URL: http://localhost:3500 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: confirm Variables
        run: echo Hello world ${{secrets.pactBrokerUsername}} $PACT_BROKER_URL $GITHUB_SHA
      - name: Install & Tests
        run: |
          npm install
          npm test
      - name: Build Image
        run: docker build -t loneconsumer .
      - name: Run Builded Image
        run: docker run -p 3001:3001 --env PACT_BROKER_URL=$PACT_BROKER_URL --env PACT_BROKER_PASSWORD=${{secrets.pactBrokerPassword}} --env PACT_BROKER_USERNAME=${{secrets.pactBrokerUsername}} --env CONSUMER_VERSION=$GITHUB_SHA --env PACT_MOCK_URL=$PACT_MOCK_URL --env PROVIDER_URL=http://localhost:3000  -t loneconsumer 
      - name: Can i Deploy
        run: |
            curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.83.0/pact-1.83.0-linux-x86_64.tar.gz tar xzf pact-1.83.0-linux-x86_64.tar.gz
            cd pact/bin
            ./pact-broker can-i-deploy -a, --pacticipant=catsConsumer -b, --broker-base-url=$PACT_BROKER_URL -u=${{secrets.pactBrokerUsername}} -p=${{secrets.pactBrokerPassword}} --latest 
  cd:
    runs-on: ubuntu-latest
    env:
        PACT_BROKER_URL: https://pact-broker.int.k8s.getmobee.com/
    steps:
      - name: Can i Deploy
        run: |
            curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.83.0/pact-1.83.0-linux-x86.tar.gz tar xzf pact-1.83.0-linux-x86.tar.gz
            cd pact/bin
            ./pact-broker can-i-deploy -a, --pacticipant=catsConsumer -b, --broker-base-url=$PACT_BROKER_URL -u=${{secrets.pactBrokerUsername}} -p=${{secrets.pactBrokerPassword}} --latest 
