name: NestConsumer CI/CD
on:
  push:
    branches:
       - master
  pull_request:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install & Tests
        run: 
          npm install
          npm test
      - name: Build Image
        run: docker build -t loneconsumer .
      - name: Run Builded Image
        run: docker run -p 3001:3001 -t loneconsumer
      - name: View Images
        run: docker ps
        
      
